services:
  api:
    image: html-analyzer:latest
    build: 
      context: .
      dockerfile: docker/api/Dockerfile 
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080

      ConnectionStrings__Db: Host=postgres;Port=5432;Database=html_analyzer_db;Username=postgres;Password=postgres
    ports: 
      - 8090:8080
  postgres:
    image: postgres:18.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: html_analyzer_db

    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql 
  pgadmin:
    image: dpage/pgadmin4:9.18
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin
      PGPASS_FILE: /pgadmin4/pgpass

      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_REPLACE_SERVERS_ON_STARTUP: "True"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - 8080:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
      - ./pgadmin/pgpass:/pgadmin4/pgpass:ro
    depends_on:
      - postgres
volumes:
  postgres-data: 
  pgadmin-data:

