namespace Analyzer.Html.Models.Common;

public enum ErrorCodeType : byte
{
    NONE,

    EMPTY_SELECTOR,
    EMPTY_ATTRIBUTE,
    EMPTY_URL_B64,
    EMPTY_ENCRYPTED_TEXT_B64,
    EMPTY_KEY_BYTES_B64,
    EMPTY_PAGE_B64,

    MISSING_ALL_PARAMETRS,

    INVALID_DECODE_URL_B64,
    INVALID_DECODE_ENCRYPTED_TEXT_B64,
    INVALID_DECODE_KEY_BYTES_B64,
    INVALID_DECODE_PAGE_B64,

    AESECB_DATA_LENGTH_NOT_MULTIPLY_OF_16B,
    AES256_KEY_NOT_32B,
    INVALID_AES_DATA,

    INVALID_PARSING_HTML_PAGE,
    INVALID_INSERTING_BY_TRANSACTION
}
